### ISSUE TITLE
No-op

### ISSUE THREAD

**Issue by kevinfu1** [kevinfu1/KVille#18]
**Describe the bug**
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at Swipeable (http://localhost:19006/static/js/bundle.js:125832:81)
    at div
    at http://localhost:19006/static/js/bundle.js:180202:25
    at TouchableOpacity (http://localhost:19006/static/js/bundle.js:179760:29)
    at Member (http://localhost:19006/static/js/bundle.js:210739:22)

**To Reproduce**
1. Go to Group Info Page
2. Click on any member
3. Change group role

**Expected behavior**
Need to identify what react state is being updated on what component

**Screenshots**

**Additional context**
Maybe a result of updating the display of the modal when changing group role which occurs after the modal is unmounted since modal is created on a separate node

**Comment by kevinfu1** [comment]
No longer issue, not exactly sure what solved it
